networks:
  default:
    name: exposed
    external: true

services:
  postgres:
    container_name: exposed-postgres
    image: postgres:16.4
    environment:
      POSTGRES_ROOT_HOST: "%"
      POSTGRES_USER: postgres
      POSTGRES_DB: exposed
      POSTGRES_PASSWORD: password
    ports:
      - ${POSTGRES_PORT:-5432}:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
